### ISSUE TITLE
no sharedpref ? 

### ISSUE THREAD

**Issue by nitneuq33** [Morthor/flutter_todo_app_talk#1]
Hello, I tried your example but data are not persistant... sharedpref package is present but not key are saved. Can you can add this in the example ? thank you

**Comment by Morthor** [comment]
Hello.

There is a branch called shared_preferences that shows you how to use the
package. You can also find the video on my YouTube channel.

**Comment by nitneuq33** [comment]
I find thank you !

Le mar. 16 juil. 2019 à 11:03, João Soares <notifications@github.com> a
écrit :

> Hello.
>
> There is a branch called shared_preferences that shows you how to use the
> package. You can also find the video on my YouTube channel.
>
